name: Release catcam client

on:
  push:
    tags: # Trigger only on version tags
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compress build artifacts
        run: zip -r dist.zip dist

      - name: Upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist.zip # Path to the compressed artifact
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Build artifacts for ${{ github.ref_name }}."
          draft: false
          prerelease: false
